//
// AccountFailedWebhooks200ResponseResultWebhookInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AccountFailedWebhooks200ResponseResultWebhookInner: Codable, JSONEncodable, Hashable {

    public var webhookId: Int?
    public var entityId: String?
    public var time: A2CDateTime?

    public init(webhookId: Int? = nil, entityId: String? = nil, time: A2CDateTime? = nil) {
        self.webhookId = webhookId
        self.entityId = entityId
        self.time = time
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case webhookId = "webhook_id"
        case entityId = "entity_id"
        case time
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(webhookId, forKey: .webhookId)
        try container.encodeIfPresent(entityId, forKey: .entityId)
        try container.encodeIfPresent(time, forKey: .time)
    }
}

