//
// AccountFailedWebhooks200ResponseResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AccountFailedWebhooks200ResponseResult: Codable, JSONEncodable, Hashable {

    public var allFailedWebhook: String?
    public var webhook: [AccountFailedWebhooks200ResponseResultWebhookInner]?

    public init(allFailedWebhook: String? = nil, webhook: [AccountFailedWebhooks200ResponseResultWebhookInner]? = nil) {
        self.allFailedWebhook = allFailedWebhook
        self.webhook = webhook
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case allFailedWebhook = "all_failed_webhook"
        case webhook
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(allFailedWebhook, forKey: .allFailedWebhook)
        try container.encodeIfPresent(webhook, forKey: .webhook)
    }
}

