//
// AccountSupportedPlatformParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AccountSupportedPlatformParams: Codable, JSONEncodable, Hashable {

    public var _required: [[AccountSupportedPlatformParamsRequiredInnerInner]]?
    public var additional: [AccountSupportedPlatformParamsRequiredInnerInner]?

    public init(_required: [[AccountSupportedPlatformParamsRequiredInnerInner]]? = nil, additional: [AccountSupportedPlatformParamsRequiredInnerInner]? = nil) {
        self._required = _required
        self.additional = additional
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case _required = "required"
        case additional
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(_required, forKey: ._required)
        try container.encodeIfPresent(additional, forKey: .additional)
    }
}

