//
// AccountSupportedPlatforms200ResponseResultSupportedPlatformsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AccountSupportedPlatforms200ResponseResultSupportedPlatformsInner: Codable, JSONEncodable, Hashable {

    public var cartId: String?
    public var cartName: String?
    public var cartVersions: String?
    public var cartMethod: String?
    public var params: AccountSupportedPlatforms200ResponseResultSupportedPlatformsInnerParams?

    public init(cartId: String? = nil, cartName: String? = nil, cartVersions: String? = nil, cartMethod: String? = nil, params: AccountSupportedPlatforms200ResponseResultSupportedPlatformsInnerParams? = nil) {
        self.cartId = cartId
        self.cartName = cartName
        self.cartVersions = cartVersions
        self.cartMethod = cartMethod
        self.params = params
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cartId = "cart_id"
        case cartName = "cart_name"
        case cartVersions = "cart_versions"
        case cartMethod = "cart_method"
        case params
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(cartId, forKey: .cartId)
        try container.encodeIfPresent(cartName, forKey: .cartName)
        try container.encodeIfPresent(cartVersions, forKey: .cartVersions)
        try container.encodeIfPresent(cartMethod, forKey: .cartMethod)
        try container.encodeIfPresent(params, forKey: .params)
    }
}

