//
// AnalyticsCustomer.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AnalyticsCustomer: Codable, JSONEncodable, Hashable {

    public var customerId: String?
    public var name: String?
    public var email: String?
    public var customerType: String?
    public var metrics: AnalyticsCustomerMetric?
    public var additionalFields: AnyCodable?
    public var customFields: AnyCodable?

    public init(customerId: String? = nil, name: String? = nil, email: String? = nil, customerType: String? = nil, metrics: AnalyticsCustomerMetric? = nil, additionalFields: AnyCodable? = nil, customFields: AnyCodable? = nil) {
        self.customerId = customerId
        self.name = name
        self.email = email
        self.customerType = customerType
        self.metrics = metrics
        self.additionalFields = additionalFields
        self.customFields = customFields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case customerId = "customer_id"
        case name
        case email
        case customerType = "customer_type"
        case metrics
        case additionalFields = "additional_fields"
        case customFields = "custom_fields"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(customerId, forKey: .customerId)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(customerType, forKey: .customerType)
        try container.encodeIfPresent(metrics, forKey: .metrics)
        try container.encodeIfPresent(additionalFields, forKey: .additionalFields)
        try container.encodeIfPresent(customFields, forKey: .customFields)
    }
}

