//
// AnalyticsMetric.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AnalyticsMetric: Codable, JSONEncodable, Hashable {

    public var ordersCount: Int?
    public var itemsSold: Int?
    public var grossSales: Double?
    public var netSales: Double?
    public var totalSales: Double?
    public var avgOrderValue: Double?
    public var discounts: Double?
    public var refunds: Double?
    public var tax: Double?
    public var shipping: Double?
    public var fees: Double?
    public var currencyId: String?
    public var additionalFields: AnyCodable?
    public var customFields: AnyCodable?

    public init(ordersCount: Int? = nil, itemsSold: Int? = nil, grossSales: Double? = nil, netSales: Double? = nil, totalSales: Double? = nil, avgOrderValue: Double? = nil, discounts: Double? = nil, refunds: Double? = nil, tax: Double? = nil, shipping: Double? = nil, fees: Double? = nil, currencyId: String? = nil, additionalFields: AnyCodable? = nil, customFields: AnyCodable? = nil) {
        self.ordersCount = ordersCount
        self.itemsSold = itemsSold
        self.grossSales = grossSales
        self.netSales = netSales
        self.totalSales = totalSales
        self.avgOrderValue = avgOrderValue
        self.discounts = discounts
        self.refunds = refunds
        self.tax = tax
        self.shipping = shipping
        self.fees = fees
        self.currencyId = currencyId
        self.additionalFields = additionalFields
        self.customFields = customFields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ordersCount = "orders_count"
        case itemsSold = "items_sold"
        case grossSales = "gross_sales"
        case netSales = "net_sales"
        case totalSales = "total_sales"
        case avgOrderValue = "avg_order_value"
        case discounts
        case refunds
        case tax
        case shipping
        case fees
        case currencyId = "currency_id"
        case additionalFields = "additional_fields"
        case customFields = "custom_fields"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(ordersCount, forKey: .ordersCount)
        try container.encodeIfPresent(itemsSold, forKey: .itemsSold)
        try container.encodeIfPresent(grossSales, forKey: .grossSales)
        try container.encodeIfPresent(netSales, forKey: .netSales)
        try container.encodeIfPresent(totalSales, forKey: .totalSales)
        try container.encodeIfPresent(avgOrderValue, forKey: .avgOrderValue)
        try container.encodeIfPresent(discounts, forKey: .discounts)
        try container.encodeIfPresent(refunds, forKey: .refunds)
        try container.encodeIfPresent(tax, forKey: .tax)
        try container.encodeIfPresent(shipping, forKey: .shipping)
        try container.encodeIfPresent(fees, forKey: .fees)
        try container.encodeIfPresent(currencyId, forKey: .currencyId)
        try container.encodeIfPresent(additionalFields, forKey: .additionalFields)
        try container.encodeIfPresent(customFields, forKey: .customFields)
    }
}

