//
// BasketLiveShippingService.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BasketLiveShippingService: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var name: String?
    public var callback: String?
    public var callbackErrCnt: Int?
    public var enabledOnStore: Bool?
    public var additionalFields: AnyCodable?
    public var customFields: AnyCodable?

    public init(id: String? = nil, name: String? = nil, callback: String? = nil, callbackErrCnt: Int? = nil, enabledOnStore: Bool? = nil, additionalFields: AnyCodable? = nil, customFields: AnyCodable? = nil) {
        self.id = id
        self.name = name
        self.callback = callback
        self.callbackErrCnt = callbackErrCnt
        self.enabledOnStore = enabledOnStore
        self.additionalFields = additionalFields
        self.customFields = customFields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case callback
        case callbackErrCnt = "callback_err_cnt"
        case enabledOnStore = "enabled_on_store"
        case additionalFields = "additional_fields"
        case customFields = "custom_fields"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(callback, forKey: .callback)
        try container.encodeIfPresent(callbackErrCnt, forKey: .callbackErrCnt)
        try container.encodeIfPresent(enabledOnStore, forKey: .enabledOnStore)
        try container.encodeIfPresent(additionalFields, forKey: .additionalFields)
        try container.encodeIfPresent(customFields, forKey: .customFields)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension BasketLiveShippingService: Identifiable {}
