//
// CartClearCache200ResponseResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CartClearCache200ResponseResult: Codable, JSONEncodable, Hashable {

    public var cacheCleared: String?

    public init(cacheCleared: String? = nil) {
        self.cacheCleared = cacheCleared
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cacheCleared = "cache_cleared"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(cacheCleared, forKey: .cacheCleared)
    }
}

