//
// CartCouponCount200ResponseResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CartCouponCount200ResponseResult: Codable, JSONEncodable, Hashable {

    public var couponsCount: String?

    public init(couponsCount: String? = nil) {
        self.couponsCount = couponsCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case couponsCount = "coupons_count"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(couponsCount, forKey: .couponsCount)
    }
}

