//
// CartList200ResponseResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CartList200ResponseResult: Codable, JSONEncodable, Hashable {

    public var supportedCarts: [CartList200ResponseResultSupportedCartsInner]?

    public init(supportedCarts: [CartList200ResponseResultSupportedCartsInner]? = nil) {
        self.supportedCarts = supportedCarts
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case supportedCarts = "supported_carts"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(supportedCarts, forKey: .supportedCarts)
    }
}

