//
// CartPickupLocation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CartPickupLocation: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var name: String?
    public var avail: Bool?
    public var address: CustomerAddress?
    public var pickupInstructions: String?
    public var expectedReadyTime: String?
    public var additionalFields: AnyCodable?
    public var customFields: AnyCodable?

    public init(id: String? = nil, name: String? = nil, avail: Bool? = nil, address: CustomerAddress? = nil, pickupInstructions: String? = nil, expectedReadyTime: String? = nil, additionalFields: AnyCodable? = nil, customFields: AnyCodable? = nil) {
        self.id = id
        self.name = name
        self.avail = avail
        self.address = address
        self.pickupInstructions = pickupInstructions
        self.expectedReadyTime = expectedReadyTime
        self.additionalFields = additionalFields
        self.customFields = customFields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case avail
        case address
        case pickupInstructions = "pickup_instructions"
        case expectedReadyTime = "expected_ready_time"
        case additionalFields = "additional_fields"
        case customFields = "custom_fields"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(avail, forKey: .avail)
        try container.encodeIfPresent(address, forKey: .address)
        try container.encodeIfPresent(pickupInstructions, forKey: .pickupInstructions)
        try container.encodeIfPresent(expectedReadyTime, forKey: .expectedReadyTime)
        try container.encodeIfPresent(additionalFields, forKey: .additionalFields)
        try container.encodeIfPresent(customFields, forKey: .customFields)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension CartPickupLocation: Identifiable {}
