//
// CategoryAdd200ResponseResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CategoryAdd200ResponseResult: Codable, JSONEncodable, Hashable {

    public var categoryId: String?

    public init(categoryId: String? = nil) {
        self.categoryId = categoryId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case categoryId = "category_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(categoryId, forKey: .categoryId)
    }
}

