//
// CategoryCount200ResponseResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CategoryCount200ResponseResult: Codable, JSONEncodable, Hashable {

    public var categoriesCount: Int?

    public init(categoriesCount: Int? = nil) {
        self.categoriesCount = categoriesCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case categoriesCount = "categories_count"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(categoriesCount, forKey: .categoriesCount)
    }
}

