//
// Country.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Country: Codable, JSONEncodable, Hashable {

    public var code2: String?
    public var code3: String?
    public var name: String?
    public var additionalFields: AnyCodable?
    public var customFields: AnyCodable?

    public init(code2: String? = nil, code3: String? = nil, name: String? = nil, additionalFields: AnyCodable? = nil, customFields: AnyCodable? = nil) {
        self.code2 = code2
        self.code3 = code3
        self.name = name
        self.additionalFields = additionalFields
        self.customFields = customFields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code2
        case code3
        case name
        case additionalFields = "additional_fields"
        case customFields = "custom_fields"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(code2, forKey: .code2)
        try container.encodeIfPresent(code3, forKey: .code3)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(additionalFields, forKey: .additionalFields)
        try container.encodeIfPresent(customFields, forKey: .customFields)
    }
}

