//
// CouponAction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CouponAction: Codable, JSONEncodable, Hashable {

    public var scope: String?
    public var applyTo: String?
    public var amount: Double?
    public var currencyCode: String?
    public var includeTax: Bool?
    public var type: String?
    public var discountedQuantity: Double?
    public var discountQuantityStep: Int?
    public var logicOperator: String?
    public var conditions: [CouponCondition]?
    public var additionalFields: AnyCodable?
    public var customFields: AnyCodable?

    public init(scope: String? = nil, applyTo: String? = nil, amount: Double? = nil, currencyCode: String? = nil, includeTax: Bool? = nil, type: String? = nil, discountedQuantity: Double? = nil, discountQuantityStep: Int? = nil, logicOperator: String? = nil, conditions: [CouponCondition]? = nil, additionalFields: AnyCodable? = nil, customFields: AnyCodable? = nil) {
        self.scope = scope
        self.applyTo = applyTo
        self.amount = amount
        self.currencyCode = currencyCode
        self.includeTax = includeTax
        self.type = type
        self.discountedQuantity = discountedQuantity
        self.discountQuantityStep = discountQuantityStep
        self.logicOperator = logicOperator
        self.conditions = conditions
        self.additionalFields = additionalFields
        self.customFields = customFields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case scope
        case applyTo = "apply_to"
        case amount
        case currencyCode = "currency_code"
        case includeTax = "include_tax"
        case type
        case discountedQuantity = "discounted_quantity"
        case discountQuantityStep = "discount_quantity_step"
        case logicOperator = "logic_operator"
        case conditions
        case additionalFields = "additional_fields"
        case customFields = "custom_fields"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(scope, forKey: .scope)
        try container.encodeIfPresent(applyTo, forKey: .applyTo)
        try container.encodeIfPresent(amount, forKey: .amount)
        try container.encodeIfPresent(currencyCode, forKey: .currencyCode)
        try container.encodeIfPresent(includeTax, forKey: .includeTax)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(discountedQuantity, forKey: .discountedQuantity)
        try container.encodeIfPresent(discountQuantityStep, forKey: .discountQuantityStep)
        try container.encodeIfPresent(logicOperator, forKey: .logicOperator)
        try container.encodeIfPresent(conditions, forKey: .conditions)
        try container.encodeIfPresent(additionalFields, forKey: .additionalFields)
        try container.encodeIfPresent(customFields, forKey: .customFields)
    }
}

