//
// CustomerAddConsentsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CustomerAddConsentsInner: Codable, JSONEncodable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case email = "email"
        case sms = "sms"
    }
    public var type: ModelType
    public var status: String
    public var optInLevel: String

    public init(type: ModelType, status: String, optInLevel: String) {
        self.type = type
        self.status = status
        self.optInLevel = optInLevel
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case status
        case optInLevel = "opt_in_level"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(status, forKey: .status)
        try container.encode(optInLevel, forKey: .optInLevel)
    }
}

