//
// CustomerCount200ResponseResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CustomerCount200ResponseResult: Codable, JSONEncodable, Hashable {

    public var customersCount: Int?

    public init(customersCount: Int? = nil) {
        self.customersCount = customersCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case customersCount = "customers_count"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(customersCount, forKey: .customersCount)
    }
}

