//
// ModelResponseTaxClassInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ModelResponseTaxClassInfo: Codable, JSONEncodable, Hashable {

    public var returnCode: Int?
    public var returnMessage: String?
    public var result: ResponseTaxClassInfoResult?
    public var additionalFields: AnyCodable?
    public var customFields: AnyCodable?

    public init(returnCode: Int? = nil, returnMessage: String? = nil, result: ResponseTaxClassInfoResult? = nil, additionalFields: AnyCodable? = nil, customFields: AnyCodable? = nil) {
        self.returnCode = returnCode
        self.returnMessage = returnMessage
        self.result = result
        self.additionalFields = additionalFields
        self.customFields = customFields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case returnCode = "return_code"
        case returnMessage = "return_message"
        case result
        case additionalFields = "additional_fields"
        case customFields = "custom_fields"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(returnCode, forKey: .returnCode)
        try container.encodeIfPresent(returnMessage, forKey: .returnMessage)
        try container.encodeIfPresent(result, forKey: .result)
        try container.encodeIfPresent(additionalFields, forKey: .additionalFields)
        try container.encodeIfPresent(customFields, forKey: .customFields)
    }
}

