//
// OrderCalculateSubtotal.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OrderCalculateSubtotal: Codable, JSONEncodable, Hashable {

    public var value: Double?
    public var tax: Double?
    public var discount: Double?
    public var additionalFields: AnyCodable?
    public var customFields: AnyCodable?

    public init(value: Double? = nil, tax: Double? = nil, discount: Double? = nil, additionalFields: AnyCodable? = nil, customFields: AnyCodable? = nil) {
        self.value = value
        self.tax = tax
        self.discount = discount
        self.additionalFields = additionalFields
        self.customFields = customFields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case value
        case tax
        case discount
        case additionalFields = "additional_fields"
        case customFields = "custom_fields"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(value, forKey: .value)
        try container.encodeIfPresent(tax, forKey: .tax)
        try container.encodeIfPresent(discount, forKey: .discount)
        try container.encodeIfPresent(additionalFields, forKey: .additionalFields)
        try container.encodeIfPresent(customFields, forKey: .customFields)
    }
}

