//
// OrderShipmentAddTrackingNumbersInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OrderShipmentAddTrackingNumbersInner: Codable, JSONEncodable, Hashable {

    public var carrierId: String?
    public var trackingNumber: String?

    public init(carrierId: String? = nil, trackingNumber: String? = nil) {
        self.carrierId = carrierId
        self.trackingNumber = trackingNumber
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case carrierId = "carrier_id"
        case trackingNumber = "tracking_number"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(carrierId, forKey: .carrierId)
        try container.encodeIfPresent(trackingNumber, forKey: .trackingNumber)
    }
}

