//
// OrderShipmentAdd200ResponseResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OrderShipmentAdd200ResponseResult: Codable, JSONEncodable, Hashable {

    public var shipmentId: String?

    public init(shipmentId: String? = nil) {
        self.shipmentId = shipmentId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case shipmentId = "shipment_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(shipmentId, forKey: .shipmentId)
    }
}

