//
// OrderAddOrderItemInnerOrderItemPropertyInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OrderAddOrderItemInnerOrderItemPropertyInner: Codable, JSONEncodable, Hashable {

    /** Ordered product property name. Where x is order item ID, y is order item property ID */
    public var orderItemPropertyName: String?
    /** Ordered product property value. Where x is order item ID, y - order item property ID */
    public var orderItemPropertyValue: String?

    public init(orderItemPropertyName: String? = nil, orderItemPropertyValue: String? = nil) {
        self.orderItemPropertyName = orderItemPropertyName
        self.orderItemPropertyValue = orderItemPropertyValue
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case orderItemPropertyName = "order_item_property_name"
        case orderItemPropertyValue = "order_item_property_value"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(orderItemPropertyName, forKey: .orderItemPropertyName)
        try container.encodeIfPresent(orderItemPropertyValue, forKey: .orderItemPropertyValue)
    }
}

