//
// OrderRefundAddItemsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OrderRefundAddItemsInner: Codable, JSONEncodable, Hashable {

    public var orderProductId: String?
    public var quantity: Int?
    public var price: Double?

    public init(orderProductId: String? = nil, quantity: Int? = nil, price: Double? = nil) {
        self.orderProductId = orderProductId
        self.quantity = quantity
        self.price = price
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case orderProductId = "order_product_id"
        case quantity
        case price
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(orderProductId, forKey: .orderProductId)
        try container.encodeIfPresent(quantity, forKey: .quantity)
        try container.encodeIfPresent(price, forKey: .price)
    }
}

