//
// OrderCalculateItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OrderCalculateItem: Codable, JSONEncodable, Hashable {

    public var productId: String?
    public var sku: String?
    public var name: String?
    public var quantity: Int?
    public var price: Double?
    public var priceIncTax: Double?
    public var taxRate: Double?
    public var unitDiscount: Double?
    public var weight: Double?
    public var weightUnit: String?
    public var barcode: String?
    public var variantId: String?
    public var options: [OrderItemOption]?
    public var additionalFields: AnyCodable?
    public var customFields: AnyCodable?

    public init(productId: String? = nil, sku: String? = nil, name: String? = nil, quantity: Int? = nil, price: Double? = nil, priceIncTax: Double? = nil, taxRate: Double? = nil, unitDiscount: Double? = nil, weight: Double? = nil, weightUnit: String? = nil, barcode: String? = nil, variantId: String? = nil, options: [OrderItemOption]? = nil, additionalFields: AnyCodable? = nil, customFields: AnyCodable? = nil) {
        self.productId = productId
        self.sku = sku
        self.name = name
        self.quantity = quantity
        self.price = price
        self.priceIncTax = priceIncTax
        self.taxRate = taxRate
        self.unitDiscount = unitDiscount
        self.weight = weight
        self.weightUnit = weightUnit
        self.barcode = barcode
        self.variantId = variantId
        self.options = options
        self.additionalFields = additionalFields
        self.customFields = customFields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case productId = "product_id"
        case sku
        case name
        case quantity
        case price
        case priceIncTax = "price_inc_tax"
        case taxRate = "tax_rate"
        case unitDiscount = "unit_discount"
        case weight
        case weightUnit = "weight_unit"
        case barcode
        case variantId = "variant_id"
        case options
        case additionalFields = "additional_fields"
        case customFields = "custom_fields"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(productId, forKey: .productId)
        try container.encodeIfPresent(sku, forKey: .sku)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(quantity, forKey: .quantity)
        try container.encodeIfPresent(price, forKey: .price)
        try container.encodeIfPresent(priceIncTax, forKey: .priceIncTax)
        try container.encodeIfPresent(taxRate, forKey: .taxRate)
        try container.encodeIfPresent(unitDiscount, forKey: .unitDiscount)
        try container.encodeIfPresent(weight, forKey: .weight)
        try container.encodeIfPresent(weightUnit, forKey: .weightUnit)
        try container.encodeIfPresent(barcode, forKey: .barcode)
        try container.encodeIfPresent(variantId, forKey: .variantId)
        try container.encodeIfPresent(options, forKey: .options)
        try container.encodeIfPresent(additionalFields, forKey: .additionalFields)
        try container.encodeIfPresent(customFields, forKey: .customFields)
    }
}

