//
// OrderCount200ResponseResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OrderCount200ResponseResult: Codable, JSONEncodable, Hashable {

    public var ordersCount: Int?

    public init(ordersCount: Int? = nil) {
        self.ordersCount = ordersCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ordersCount = "orders_count"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(ordersCount, forKey: .ordersCount)
    }
}

