//
// OrderAbandoned.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OrderAbandoned: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var customer: BaseCustomer?
    public var basketId: String?
    public var basketUrl: String?
    public var createdAt: A2CDateTime?
    public var modifiedAt: A2CDateTime?
    public var currency: Currency?
    public var totals: OrderTotals?
    public var orderProducts: [OrderItem]?
    public var additionalFields: AnyCodable?
    public var customFields: AnyCodable?

    public init(id: String? = nil, customer: BaseCustomer? = nil, basketId: String? = nil, basketUrl: String? = nil, createdAt: A2CDateTime? = nil, modifiedAt: A2CDateTime? = nil, currency: Currency? = nil, totals: OrderTotals? = nil, orderProducts: [OrderItem]? = nil, additionalFields: AnyCodable? = nil, customFields: AnyCodable? = nil) {
        self.id = id
        self.customer = customer
        self.basketId = basketId
        self.basketUrl = basketUrl
        self.createdAt = createdAt
        self.modifiedAt = modifiedAt
        self.currency = currency
        self.totals = totals
        self.orderProducts = orderProducts
        self.additionalFields = additionalFields
        self.customFields = customFields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case customer
        case basketId = "basket_id"
        case basketUrl = "basket_url"
        case createdAt = "created_at"
        case modifiedAt = "modified_at"
        case currency
        case totals
        case orderProducts = "order_products"
        case additionalFields = "additional_fields"
        case customFields = "custom_fields"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(customer, forKey: .customer)
        try container.encodeIfPresent(basketId, forKey: .basketId)
        try container.encodeIfPresent(basketUrl, forKey: .basketUrl)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(modifiedAt, forKey: .modifiedAt)
        try container.encodeIfPresent(currency, forKey: .currency)
        try container.encodeIfPresent(totals, forKey: .totals)
        try container.encodeIfPresent(orderProducts, forKey: .orderProducts)
        try container.encodeIfPresent(additionalFields, forKey: .additionalFields)
        try container.encodeIfPresent(customFields, forKey: .customFields)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension OrderAbandoned: Identifiable {}
