//
// OrderShipmentTrackingAdd.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OrderShipmentTrackingAdd: Codable, JSONEncodable, Hashable {

    /** Defines the order id */
    public var orderId: String?
    /** Shipment id indicates the number of delivery */
    public var shipmentId: String
    /** Defines tracking carrier id */
    public var carrierId: String?
    /** Store Id */
    public var storeId: String?
    /** Defines name of the company which provides shipment tracking */
    public var trackingProvider: String?
    /** Defines tracking number */
    public var trackingNumber: String
    /** Defines custom tracking link */
    public var trackingLink: String?
    /** Send notifications to customer after tracking was created */
    public var sendNotifications: Bool? = false
    /** A unique identifier associated with a specific request. Repeated requests with the same <strong>idempotency_key</strong> return a cached response without re-executing the business logic. <strong>Please note that the cache lifetime is 15 minutes.</strong> */
    public var idempotencyKey: String?

    public init(orderId: String? = nil, shipmentId: String, carrierId: String? = nil, storeId: String? = nil, trackingProvider: String? = nil, trackingNumber: String, trackingLink: String? = nil, sendNotifications: Bool? = false, idempotencyKey: String? = nil) {
        self.orderId = orderId
        self.shipmentId = shipmentId
        self.carrierId = carrierId
        self.storeId = storeId
        self.trackingProvider = trackingProvider
        self.trackingNumber = trackingNumber
        self.trackingLink = trackingLink
        self.sendNotifications = sendNotifications
        self.idempotencyKey = idempotencyKey
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case orderId = "order_id"
        case shipmentId = "shipment_id"
        case carrierId = "carrier_id"
        case storeId = "store_id"
        case trackingProvider = "tracking_provider"
        case trackingNumber = "tracking_number"
        case trackingLink = "tracking_link"
        case sendNotifications = "send_notifications"
        case idempotencyKey = "idempotency_key"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(orderId, forKey: .orderId)
        try container.encode(shipmentId, forKey: .shipmentId)
        try container.encodeIfPresent(carrierId, forKey: .carrierId)
        try container.encodeIfPresent(storeId, forKey: .storeId)
        try container.encodeIfPresent(trackingProvider, forKey: .trackingProvider)
        try container.encode(trackingNumber, forKey: .trackingNumber)
        try container.encodeIfPresent(trackingLink, forKey: .trackingLink)
        try container.encodeIfPresent(sendNotifications, forKey: .sendNotifications)
        try container.encodeIfPresent(idempotencyKey, forKey: .idempotencyKey)
    }
}

