//
// Pagination.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Pagination: Codable, JSONEncodable, Hashable {

    public var previous: String?
    public var next: String?
    public var additionalFields: AnyCodable?
    public var customFields: AnyCodable?

    public init(previous: String? = nil, next: String? = nil, additionalFields: AnyCodable? = nil, customFields: AnyCodable? = nil) {
        self.previous = previous
        self.next = next
        self.additionalFields = additionalFields
        self.customFields = customFields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case previous
        case next
        case additionalFields = "additional_fields"
        case customFields = "custom_fields"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(previous, forKey: .previous)
        try container.encodeIfPresent(next, forKey: .next)
        try container.encodeIfPresent(additionalFields, forKey: .additionalFields)
        try container.encodeIfPresent(customFields, forKey: .customFields)
    }
}

