//
// ProductUpdateBatchPayloadInnerAdvancedPricesInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProductUpdateBatchPayloadInnerAdvancedPricesInner: Codable, JSONEncodable, Hashable {

    public var value: Double
    public var groupId: Int?
    public var quantity: Double

    public init(value: Double, groupId: Int? = nil, quantity: Double) {
        self.value = value
        self.groupId = groupId
        self.quantity = quantity
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case value
        case groupId = "group_id"
        case quantity
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(value, forKey: .value)
        try container.encodeIfPresent(groupId, forKey: .groupId)
        try container.encode(quantity, forKey: .quantity)
    }
}

