//
// ProductAddCertificationsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProductAddCertificationsInner: Codable, JSONEncodable, Hashable {

    /** Certification ID */
    public var id: String
    /** Certification images */
    public var images: [ProductAddCertificationsInnerImagesInner]?
    /** Certification files */
    public var files: [ProductAddCertificationsInnerFilesInner]?

    public init(id: String, images: [ProductAddCertificationsInnerImagesInner]? = nil, files: [ProductAddCertificationsInnerFilesInner]? = nil) {
        self.id = id
        self.images = images
        self.files = files
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case images
        case files
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(images, forKey: .images)
        try container.encodeIfPresent(files, forKey: .files)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ProductAddCertificationsInner: Identifiable {}
