//
// ProductVariantPriceUpdate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProductVariantPriceUpdate: Codable, JSONEncodable, Hashable {

    /** Defines the variant where the price has to be updated */
    public var id: String?
    /** Product id */
    public var productId: String?
    /** Defines variants's group prices */
    public var groupPrices: [ProductPriceUpdateGroupPricesInner]

    public init(id: String? = nil, productId: String? = nil, groupPrices: [ProductPriceUpdateGroupPricesInner]) {
        self.id = id
        self.productId = productId
        self.groupPrices = groupPrices
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case productId = "product_id"
        case groupPrices = "group_prices"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(productId, forKey: .productId)
        try container.encode(groupPrices, forKey: .groupPrices)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ProductVariantPriceUpdate: Identifiable {}
