//
// ProductVariantUpdateBatchPayloadInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProductVariantUpdateBatchPayloadInner: Codable, JSONEncodable, Hashable {

    public static let metaKeywordsRule = ArrayRule(minItems: 1, maxItems: nil, uniqueItems: false)
    public static let storesIdsRule = ArrayRule(minItems: 1, maxItems: nil, uniqueItems: false)
    public static let imagesRule = ArrayRule(minItems: 1, maxItems: nil, uniqueItems: false)
    public static let productImagesIdsRule = ArrayRule(minItems: 1, maxItems: nil, uniqueItems: false)
    public var id: String
    public var productId: String
    public var name: String?
    public var description: String?
    public var shortDescription: String?
    public var sku: String?
    public var upc: String?
    public var mpn: String?
    public var gtin: String?
    public var isbn: String?
    public var status: String?
    public var price: Double?
    public var specialPrice: Double?
    public var costPrice: Double?
    public var retailPrice: Double?
    /** If an empty array is passed, all entries will be deleted when the 'nested_items_update_behaviour' parameter is set to 'replace'. */
    public var advancedPrices: [ProductUpdateBatchPayloadInnerAdvancedPricesInner]?
    public var quantity: Double?
    public var reserveQuantity: Double?
    public var increaseQuantity: Double?
    public var reduceQuantity: Double?
    public var warehouseId: String?
    public var manufacturerId: String?
    public var weight: Double?
    public var height: Double?
    public var length: Double?
    public var width: Double?
    public var storeId: String?
    public var langId: String?
    public var taxClassId: String?
    public var backorderStatus: String?
    public var visible: String?
    public var isDefault: Bool?
    public var inStock: Bool?
    public var isVirtual: Bool?
    public var downloadable: Bool?
    public var manageStock: Bool?
    public var isFreeShipping: Bool?
    public var seoUrl: String?
    public var metaTitle: String?
    public var metaDescription: String?
    public var metaKeywords: [String]?
    /** If an empty array is passed, all entries will be deleted when the 'nested_items_update_behaviour' parameter is set to 'replace'. */
    public var categoriesIds: [String]?
    public var storesIds: [String]?
    /** The passed items will completely replace the original items */
    public var images: [ProductAddBatchPayloadInnerImagesInner]?
    public var productImagesIds: [String]?
    /** If an empty array is passed, all entries will be deleted when the 'nested_items_update_behaviour' parameter is set to 'replace'. */
    public var relatedProductsIds: [String]?
    /** If an empty array is passed, all entries will be deleted when the 'nested_items_update_behaviour' parameter is set to 'replace'. */
    public var upSellProductsIds: [String]?
    /** If an empty array is passed, all entries will be deleted when the 'nested_items_update_behaviour' parameter is set to 'replace'. */
    public var crossSellProductsIds: [String]?

    public init(id: String, productId: String, name: String? = nil, description: String? = nil, shortDescription: String? = nil, sku: String? = nil, upc: String? = nil, mpn: String? = nil, gtin: String? = nil, isbn: String? = nil, status: String? = nil, price: Double? = nil, specialPrice: Double? = nil, costPrice: Double? = nil, retailPrice: Double? = nil, advancedPrices: [ProductUpdateBatchPayloadInnerAdvancedPricesInner]? = nil, quantity: Double? = nil, reserveQuantity: Double? = nil, increaseQuantity: Double? = nil, reduceQuantity: Double? = nil, warehouseId: String? = nil, manufacturerId: String? = nil, weight: Double? = nil, height: Double? = nil, length: Double? = nil, width: Double? = nil, storeId: String? = nil, langId: String? = nil, taxClassId: String? = nil, backorderStatus: String? = nil, visible: String? = nil, isDefault: Bool? = nil, inStock: Bool? = nil, isVirtual: Bool? = nil, downloadable: Bool? = nil, manageStock: Bool? = nil, isFreeShipping: Bool? = nil, seoUrl: String? = nil, metaTitle: String? = nil, metaDescription: String? = nil, metaKeywords: [String]? = nil, categoriesIds: [String]? = nil, storesIds: [String]? = nil, images: [ProductAddBatchPayloadInnerImagesInner]? = nil, productImagesIds: [String]? = nil, relatedProductsIds: [String]? = nil, upSellProductsIds: [String]? = nil, crossSellProductsIds: [String]? = nil) {
        self.id = id
        self.productId = productId
        self.name = name
        self.description = description
        self.shortDescription = shortDescription
        self.sku = sku
        self.upc = upc
        self.mpn = mpn
        self.gtin = gtin
        self.isbn = isbn
        self.status = status
        self.price = price
        self.specialPrice = specialPrice
        self.costPrice = costPrice
        self.retailPrice = retailPrice
        self.advancedPrices = advancedPrices
        self.quantity = quantity
        self.reserveQuantity = reserveQuantity
        self.increaseQuantity = increaseQuantity
        self.reduceQuantity = reduceQuantity
        self.warehouseId = warehouseId
        self.manufacturerId = manufacturerId
        self.weight = weight
        self.height = height
        self.length = length
        self.width = width
        self.storeId = storeId
        self.langId = langId
        self.taxClassId = taxClassId
        self.backorderStatus = backorderStatus
        self.visible = visible
        self.isDefault = isDefault
        self.inStock = inStock
        self.isVirtual = isVirtual
        self.downloadable = downloadable
        self.manageStock = manageStock
        self.isFreeShipping = isFreeShipping
        self.seoUrl = seoUrl
        self.metaTitle = metaTitle
        self.metaDescription = metaDescription
        self.metaKeywords = metaKeywords
        self.categoriesIds = categoriesIds
        self.storesIds = storesIds
        self.images = images
        self.productImagesIds = productImagesIds
        self.relatedProductsIds = relatedProductsIds
        self.upSellProductsIds = upSellProductsIds
        self.crossSellProductsIds = crossSellProductsIds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case productId = "product_id"
        case name
        case description
        case shortDescription = "short_description"
        case sku
        case upc
        case mpn
        case gtin
        case isbn
        case status
        case price
        case specialPrice = "special_price"
        case costPrice = "cost_price"
        case retailPrice = "retail_price"
        case advancedPrices = "advanced_prices"
        case quantity
        case reserveQuantity = "reserve_quantity"
        case increaseQuantity = "increase_quantity"
        case reduceQuantity = "reduce_quantity"
        case warehouseId = "warehouse_id"
        case manufacturerId = "manufacturer_id"
        case weight
        case height
        case length
        case width
        case storeId = "store_id"
        case langId = "lang_id"
        case taxClassId = "tax_class_id"
        case backorderStatus = "backorder_status"
        case visible
        case isDefault = "is_default"
        case inStock = "in_stock"
        case isVirtual = "is_virtual"
        case downloadable
        case manageStock = "manage_stock"
        case isFreeShipping = "is_free_shipping"
        case seoUrl = "seo_url"
        case metaTitle = "meta_title"
        case metaDescription = "meta_description"
        case metaKeywords = "meta_keywords"
        case categoriesIds = "categories_ids"
        case storesIds = "stores_ids"
        case images
        case productImagesIds = "product_images_ids"
        case relatedProductsIds = "related_products_ids"
        case upSellProductsIds = "up_sell_products_ids"
        case crossSellProductsIds = "cross_sell_products_ids"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(productId, forKey: .productId)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(shortDescription, forKey: .shortDescription)
        try container.encodeIfPresent(sku, forKey: .sku)
        try container.encodeIfPresent(upc, forKey: .upc)
        try container.encodeIfPresent(mpn, forKey: .mpn)
        try container.encodeIfPresent(gtin, forKey: .gtin)
        try container.encodeIfPresent(isbn, forKey: .isbn)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(price, forKey: .price)
        try container.encodeIfPresent(specialPrice, forKey: .specialPrice)
        try container.encodeIfPresent(costPrice, forKey: .costPrice)
        try container.encodeIfPresent(retailPrice, forKey: .retailPrice)
        try container.encodeIfPresent(advancedPrices, forKey: .advancedPrices)
        try container.encodeIfPresent(quantity, forKey: .quantity)
        try container.encodeIfPresent(reserveQuantity, forKey: .reserveQuantity)
        try container.encodeIfPresent(increaseQuantity, forKey: .increaseQuantity)
        try container.encodeIfPresent(reduceQuantity, forKey: .reduceQuantity)
        try container.encodeIfPresent(warehouseId, forKey: .warehouseId)
        try container.encodeIfPresent(manufacturerId, forKey: .manufacturerId)
        try container.encodeIfPresent(weight, forKey: .weight)
        try container.encodeIfPresent(height, forKey: .height)
        try container.encodeIfPresent(length, forKey: .length)
        try container.encodeIfPresent(width, forKey: .width)
        try container.encodeIfPresent(storeId, forKey: .storeId)
        try container.encodeIfPresent(langId, forKey: .langId)
        try container.encodeIfPresent(taxClassId, forKey: .taxClassId)
        try container.encodeIfPresent(backorderStatus, forKey: .backorderStatus)
        try container.encodeIfPresent(visible, forKey: .visible)
        try container.encodeIfPresent(isDefault, forKey: .isDefault)
        try container.encodeIfPresent(inStock, forKey: .inStock)
        try container.encodeIfPresent(isVirtual, forKey: .isVirtual)
        try container.encodeIfPresent(downloadable, forKey: .downloadable)
        try container.encodeIfPresent(manageStock, forKey: .manageStock)
        try container.encodeIfPresent(isFreeShipping, forKey: .isFreeShipping)
        try container.encodeIfPresent(seoUrl, forKey: .seoUrl)
        try container.encodeIfPresent(metaTitle, forKey: .metaTitle)
        try container.encodeIfPresent(metaDescription, forKey: .metaDescription)
        try container.encodeIfPresent(metaKeywords, forKey: .metaKeywords)
        try container.encodeIfPresent(categoriesIds, forKey: .categoriesIds)
        try container.encodeIfPresent(storesIds, forKey: .storesIds)
        try container.encodeIfPresent(images, forKey: .images)
        try container.encodeIfPresent(productImagesIds, forKey: .productImagesIds)
        try container.encodeIfPresent(relatedProductsIds, forKey: .relatedProductsIds)
        try container.encodeIfPresent(upSellProductsIds, forKey: .upSellProductsIds)
        try container.encodeIfPresent(crossSellProductsIds, forKey: .crossSellProductsIds)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ProductVariantUpdateBatchPayloadInner: Identifiable {}
