//
// ProductVariantAddAttributesInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProductVariantAddAttributesInner: Codable, JSONEncodable, Hashable {

    public var attributeName: String?
    public var attributeValue: String?
    public var attributePrice: Double?
    public var attributeWeight: Double?

    public init(attributeName: String? = nil, attributeValue: String? = nil, attributePrice: Double? = nil, attributeWeight: Double? = nil) {
        self.attributeName = attributeName
        self.attributeValue = attributeValue
        self.attributePrice = attributePrice
        self.attributeWeight = attributeWeight
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case attributeName = "attribute_name"
        case attributeValue = "attribute_value"
        case attributePrice = "attribute_price"
        case attributeWeight = "attribute_weight"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(attributeName, forKey: .attributeName)
        try container.encodeIfPresent(attributeValue, forKey: .attributeValue)
        try container.encodeIfPresent(attributePrice, forKey: .attributePrice)
        try container.encodeIfPresent(attributeWeight, forKey: .attributeWeight)
    }
}

