//
// ProductVariantPriceAdd.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProductVariantPriceAdd: Codable, JSONEncodable, Hashable {

    /** Defines the variant to which the price has to be added */
    public var id: String?
    /** Product id */
    public var productId: String?
    /** Defines variants's group prices */
    public var groupPrices: [ProductAddGroupPricesInner]
    /** Store Id */
    public var storeId: String?

    public init(id: String? = nil, productId: String? = nil, groupPrices: [ProductAddGroupPricesInner], storeId: String? = nil) {
        self.id = id
        self.productId = productId
        self.groupPrices = groupPrices
        self.storeId = storeId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case productId = "product_id"
        case groupPrices = "group_prices"
        case storeId = "store_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(productId, forKey: .productId)
        try container.encode(groupPrices, forKey: .groupPrices)
        try container.encodeIfPresent(storeId, forKey: .storeId)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ProductVariantPriceAdd: Identifiable {}
