//
// ProductOptionAddValuesInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProductOptionAddValuesInner: Codable, JSONEncodable, Hashable {

    public static let valueRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let displayValueRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var value: String
    public var displayValue: String?
    public var isDefault: Bool? = false

    public init(value: String, displayValue: String? = nil, isDefault: Bool? = false) {
        self.value = value
        self.displayValue = displayValue
        self.isDefault = isDefault
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case value
        case displayValue = "display_value"
        case isDefault = "is_default"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(value, forKey: .value)
        try container.encodeIfPresent(displayValue, forKey: .displayValue)
        try container.encodeIfPresent(isDefault, forKey: .isDefault)
    }
}

