//
// ProductAddBestOffer.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The price at which Best Offers are automatically accepted.&lt;hr&gt;&lt;div style&#x3D;\&quot;font-style:normal\&quot;&gt;Param structure:&lt;div style&#x3D;\&quot;margin-left: 2%;\&quot;&gt;&lt;code style&#x3D;\&quot;padding:0; background-color:#ffffff;font-size:85%;font-family:monospace;\&quot;&gt;best_offer[&lt;b&gt;minimum_offer_price&lt;/b&gt;] &#x3D; decimal&lt;/br&gt;best_offer[&lt;b&gt;auto_accept_price&lt;/b&gt;] &#x3D; decimal&lt;/br&gt;&lt;/code&gt;&lt;/div&gt;&lt;/div&gt; */
public struct ProductAddBestOffer: Codable, JSONEncodable, Hashable {

    public var minimumOfferPrice: Double?
    public var autoAcceptPrice: Double?

    public init(minimumOfferPrice: Double? = nil, autoAcceptPrice: Double? = nil) {
        self.minimumOfferPrice = minimumOfferPrice
        self.autoAcceptPrice = autoAcceptPrice
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case minimumOfferPrice = "minimum_offer_price"
        case autoAcceptPrice = "auto_accept_price"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(minimumOfferPrice, forKey: .minimumOfferPrice)
        try container.encodeIfPresent(autoAcceptPrice, forKey: .autoAcceptPrice)
    }
}

