//
// ProductDeleteBatch.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProductDeleteBatch: Codable, JSONEncodable, Hashable {

    public static let payloadRule = ArrayRule(minItems: 1, maxItems: 250, uniqueItems: false)
    /** Contains an array of product deletion requests, each including the product ID. */
    public var payload: [ProductDeleteBatchPayloadInner]
    /** A unique identifier associated with a specific request. Repeated requests with the same <strong>idempotency_key</strong> return a cached response without re-executing the business logic. <strong>Please note that the cache lifetime is 15 minutes.</strong> */
    public var idempotencyKey: String?

    public init(payload: [ProductDeleteBatchPayloadInner], idempotencyKey: String? = nil) {
        self.payload = payload
        self.idempotencyKey = idempotencyKey
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case payload
        case idempotencyKey = "idempotency_key"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(payload, forKey: .payload)
        try container.encodeIfPresent(idempotencyKey, forKey: .idempotencyKey)
    }
}

