//
// ProductVariantImageAdd.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProductVariantImageAdd: Codable, JSONEncodable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case small = "small"
        case base = "base"
        case additional = "additional"
        case thumbnail = "thumbnail"
    }
    /** Defines product id where the variant image has to be added */
    public var productId: String?
    /** Defines product's variants specified by variant id */
    public var productVariantId: String
    /** Defines image's name */
    public var imageName: String
    /** Defines image's types that are specified by comma-separated list */
    public var type: ModelType = .base
    /** Defines URL of the image that has to be added */
    public var url: String?
    /** Content(body) encoded in base64 of image file */
    public var content: String?
    /** Defines alternative text that has to be attached to the picture */
    public var label: String?
    /** Mime type of image http://en.wikipedia.org/wiki/Internet_media_type. */
    public var mime: String?
    /** Defines image’s position in the list */
    public var position: Int? = 0
    /** Store Id */
    public var storeId: String?
    /** Defines option id of the product variant for which the image will be added */
    public var optionId: String?

    public init(productId: String? = nil, productVariantId: String, imageName: String, type: ModelType = .base, url: String? = nil, content: String? = nil, label: String? = nil, mime: String? = nil, position: Int? = 0, storeId: String? = nil, optionId: String? = nil) {
        self.productId = productId
        self.productVariantId = productVariantId
        self.imageName = imageName
        self.type = type
        self.url = url
        self.content = content
        self.label = label
        self.mime = mime
        self.position = position
        self.storeId = storeId
        self.optionId = optionId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case productId = "product_id"
        case productVariantId = "product_variant_id"
        case imageName = "image_name"
        case type
        case url
        case content
        case label
        case mime
        case position
        case storeId = "store_id"
        case optionId = "option_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(productId, forKey: .productId)
        try container.encode(productVariantId, forKey: .productVariantId)
        try container.encode(imageName, forKey: .imageName)
        try container.encode(type, forKey: .type)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(content, forKey: .content)
        try container.encodeIfPresent(label, forKey: .label)
        try container.encodeIfPresent(mime, forKey: .mime)
        try container.encodeIfPresent(position, forKey: .position)
        try container.encodeIfPresent(storeId, forKey: .storeId)
        try container.encodeIfPresent(optionId, forKey: .optionId)
    }
}

