//
// ProductTaxAdd200ResponseResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProductTaxAdd200ResponseResult: Codable, JSONEncodable, Hashable {

    public var taxClassId: String?

    public init(taxClassId: String? = nil) {
        self.taxClassId = taxClassId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case taxClassId = "tax_class_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(taxClassId, forKey: .taxClassId)
    }
}

