//
// ProductOptionAssign200ResponseResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProductOptionAssign200ResponseResult: Codable, JSONEncodable, Hashable {

    public var productOptionId: String?

    public init(productOptionId: String? = nil) {
        self.productOptionId = productOptionId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case productOptionId = "product_option_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(productOptionId, forKey: .productOptionId)
    }
}

