//
// ProductVariantList200ResponseResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProductVariantList200ResponseResult: Codable, JSONEncodable, Hashable {

    public var variant: [Product]?

    public init(variant: [Product]? = nil) {
        self.variant = variant
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case variant
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(variant, forKey: .variant)
    }
}

