//
// ProductOptionAdd200ResponseResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProductOptionAdd200ResponseResult: Codable, JSONEncodable, Hashable {

    public var optionId: String?
    public var productOptionId: String?
    public var productValueIds: String?

    public init(optionId: String? = nil, productOptionId: String? = nil, productValueIds: String? = nil) {
        self.optionId = optionId
        self.productOptionId = productOptionId
        self.productValueIds = productValueIds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case optionId = "option_id"
        case productOptionId = "product_option_id"
        case productValueIds = "product_value_ids"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(optionId, forKey: .optionId)
        try container.encodeIfPresent(productOptionId, forKey: .productOptionId)
        try container.encodeIfPresent(productValueIds, forKey: .productValueIds)
    }
}

