//
// ProductAttributeValueSet200ResponseResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProductAttributeValueSet200ResponseResult: Codable, JSONEncodable, Hashable {

    public var productId: String?
    public var attributeId: String?
    public var valueId: String?

    public init(productId: String? = nil, attributeId: String? = nil, valueId: String? = nil) {
        self.productId = productId
        self.attributeId = attributeId
        self.valueId = valueId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case productId = "product_id"
        case attributeId = "attribute_id"
        case valueId = "value_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(productId, forKey: .productId)
        try container.encodeIfPresent(attributeId, forKey: .attributeId)
        try container.encodeIfPresent(valueId, forKey: .valueId)
    }
}

