//
// ProductPriceAdd.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProductPriceAdd: Codable, JSONEncodable, Hashable {

    /** Defines the product to which the price has to be added */
    public var productId: String?
    /** Defines product's group prices */
    public var groupPrices: [ProductAddGroupPricesInner]?
    /** Store Id */
    public var storeId: String?
    /** A unique identifier associated with a specific request. Repeated requests with the same <strong>idempotency_key</strong> return a cached response without re-executing the business logic. <strong>Please note that the cache lifetime is 15 minutes.</strong> */
    public var idempotencyKey: String?

    public init(productId: String? = nil, groupPrices: [ProductAddGroupPricesInner]? = nil, storeId: String? = nil, idempotencyKey: String? = nil) {
        self.productId = productId
        self.groupPrices = groupPrices
        self.storeId = storeId
        self.idempotencyKey = idempotencyKey
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case productId = "product_id"
        case groupPrices = "group_prices"
        case storeId = "store_id"
        case idempotencyKey = "idempotency_key"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(productId, forKey: .productId)
        try container.encodeIfPresent(groupPrices, forKey: .groupPrices)
        try container.encodeIfPresent(storeId, forKey: .storeId)
        try container.encodeIfPresent(idempotencyKey, forKey: .idempotencyKey)
    }
}

