//
// ResponseOrderFulfillmentStatusListResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ResponseOrderFulfillmentStatusListResult: Codable, JSONEncodable, Hashable {

    public var count: Int?
    public var orderFulfillmentStatuses: [Status]?
    public var additionalFields: AnyCodable?
    public var customFields: AnyCodable?

    public init(count: Int? = nil, orderFulfillmentStatuses: [Status]? = nil, additionalFields: AnyCodable? = nil, customFields: AnyCodable? = nil) {
        self.count = count
        self.orderFulfillmentStatuses = orderFulfillmentStatuses
        self.additionalFields = additionalFields
        self.customFields = customFields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case count
        case orderFulfillmentStatuses = "order_fulfillment_statuses"
        case additionalFields = "additional_fields"
        case customFields = "custom_fields"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(count, forKey: .count)
        try container.encodeIfPresent(orderFulfillmentStatuses, forKey: .orderFulfillmentStatuses)
        try container.encodeIfPresent(additionalFields, forKey: .additionalFields)
        try container.encodeIfPresent(customFields, forKey: .customFields)
    }
}

