//
// ResponseAccountSupportedPlatformsResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ResponseAccountSupportedPlatformsResult: Codable, JSONEncodable, Hashable {

    public var supportedPlatformsCount: Int?
    public var supportedPlatforms: [AccountSupportedPlatform]?
    public var additionalFields: AnyCodable?
    public var customFields: AnyCodable?

    public init(supportedPlatformsCount: Int? = nil, supportedPlatforms: [AccountSupportedPlatform]? = nil, additionalFields: AnyCodable? = nil, customFields: AnyCodable? = nil) {
        self.supportedPlatformsCount = supportedPlatformsCount
        self.supportedPlatforms = supportedPlatforms
        self.additionalFields = additionalFields
        self.customFields = customFields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case supportedPlatformsCount = "supported_platforms_count"
        case supportedPlatforms = "supported_platforms"
        case additionalFields = "additional_fields"
        case customFields = "custom_fields"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(supportedPlatformsCount, forKey: .supportedPlatformsCount)
        try container.encodeIfPresent(supportedPlatforms, forKey: .supportedPlatforms)
        try container.encodeIfPresent(additionalFields, forKey: .additionalFields)
        try container.encodeIfPresent(customFields, forKey: .customFields)
    }
}

