//
// ResponseProductListResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ResponseProductListResult: Codable, JSONEncodable, Hashable {

    public var productsCount: Int?
    public var product: [Product]?
    public var additionalFields: AnyCodable?
    public var customFields: AnyCodable?

    public init(productsCount: Int? = nil, product: [Product]? = nil, additionalFields: AnyCodable? = nil, customFields: AnyCodable? = nil) {
        self.productsCount = productsCount
        self.product = product
        self.additionalFields = additionalFields
        self.customFields = customFields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case productsCount = "products_count"
        case product
        case additionalFields = "additional_fields"
        case customFields = "custom_fields"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(productsCount, forKey: .productsCount)
        try container.encodeIfPresent(product, forKey: .product)
        try container.encodeIfPresent(additionalFields, forKey: .additionalFields)
        try container.encodeIfPresent(customFields, forKey: .customFields)
    }
}

