//
// ResponseProductOptionListResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ResponseProductOptionListResult: Codable, JSONEncodable, Hashable {

    public var option: [ProductOption]?
    public var additionalFields: AnyCodable?
    public var customFields: AnyCodable?

    public init(option: [ProductOption]? = nil, additionalFields: AnyCodable? = nil, customFields: AnyCodable? = nil) {
        self.option = option
        self.additionalFields = additionalFields
        self.customFields = customFields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case option
        case additionalFields = "additional_fields"
        case customFields = "custom_fields"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(option, forKey: .option)
        try container.encodeIfPresent(additionalFields, forKey: .additionalFields)
        try container.encodeIfPresent(customFields, forKey: .customFields)
    }
}

