//
// ResponseProductBrandListResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ResponseProductBrandListResult: Codable, JSONEncodable, Hashable {

    public var totalCount: Int?
    public var brands: [Brand]?
    public var additionalFields: AnyCodable?
    public var customFields: AnyCodable?

    public init(totalCount: Int? = nil, brands: [Brand]? = nil, additionalFields: AnyCodable? = nil, customFields: AnyCodable? = nil) {
        self.totalCount = totalCount
        self.brands = brands
        self.additionalFields = additionalFields
        self.customFields = customFields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case totalCount = "total_count"
        case brands
        case additionalFields = "additional_fields"
        case customFields = "custom_fields"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(totalCount, forKey: .totalCount)
        try container.encodeIfPresent(brands, forKey: .brands)
        try container.encodeIfPresent(additionalFields, forKey: .additionalFields)
        try container.encodeIfPresent(customFields, forKey: .customFields)
    }
}

