//
// ResponseOrderTransactionListResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ResponseOrderTransactionListResult: Codable, JSONEncodable, Hashable {

    public var transactionsCount: Int?
    public var transactions: [OrderTransaction]?
    public var additionalFields: AnyCodable?
    public var customFields: AnyCodable?

    public init(transactionsCount: Int? = nil, transactions: [OrderTransaction]? = nil, additionalFields: AnyCodable? = nil, customFields: AnyCodable? = nil) {
        self.transactionsCount = transactionsCount
        self.transactions = transactions
        self.additionalFields = additionalFields
        self.customFields = customFields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case transactionsCount = "transactions_count"
        case transactions
        case additionalFields = "additional_fields"
        case customFields = "custom_fields"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(transactionsCount, forKey: .transactionsCount)
        try container.encodeIfPresent(transactions, forKey: .transactions)
        try container.encodeIfPresent(additionalFields, forKey: .additionalFields)
        try container.encodeIfPresent(customFields, forKey: .customFields)
    }
}

