//
// ResponseAttributeTypeListResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ResponseAttributeTypeListResult: Codable, JSONEncodable, Hashable {

    public var itemsCount: Int?
    public var attributeType: [String]?
    public var additionalFields: AnyCodable?
    public var customFields: AnyCodable?

    public init(itemsCount: Int? = nil, attributeType: [String]? = nil, additionalFields: AnyCodable? = nil, customFields: AnyCodable? = nil) {
        self.itemsCount = itemsCount
        self.attributeType = attributeType
        self.additionalFields = additionalFields
        self.customFields = customFields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case itemsCount = "items_count"
        case attributeType = "attribute_type"
        case additionalFields = "additional_fields"
        case customFields = "custom_fields"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(itemsCount, forKey: .itemsCount)
        try container.encodeIfPresent(attributeType, forKey: .attributeType)
        try container.encodeIfPresent(additionalFields, forKey: .additionalFields)
        try container.encodeIfPresent(customFields, forKey: .customFields)
    }
}

