//
// ResponseAttributeGroupListResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ResponseAttributeGroupListResult: Codable, JSONEncodable, Hashable {

    public var group: [StoreAttributeGroup]?
    public var additionalFields: AnyCodable?
    public var customFields: AnyCodable?

    public init(group: [StoreAttributeGroup]? = nil, additionalFields: AnyCodable? = nil, customFields: AnyCodable? = nil) {
        self.group = group
        self.additionalFields = additionalFields
        self.customFields = customFields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case group
        case additionalFields = "additional_fields"
        case customFields = "custom_fields"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(group, forKey: .group)
        try container.encodeIfPresent(additionalFields, forKey: .additionalFields)
        try container.encodeIfPresent(customFields, forKey: .customFields)
    }
}

