//
// ResponseCartCatalogPriceRulesCountResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ResponseCartCatalogPriceRulesCountResult: Codable, JSONEncodable, Hashable {

    public var catalogPriceRulesCount: Int?
    public var additionalFields: AnyCodable?
    public var customFields: AnyCodable?

    public init(catalogPriceRulesCount: Int? = nil, additionalFields: AnyCodable? = nil, customFields: AnyCodable? = nil) {
        self.catalogPriceRulesCount = catalogPriceRulesCount
        self.additionalFields = additionalFields
        self.customFields = customFields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case catalogPriceRulesCount = "catalog_price_rules_count"
        case additionalFields = "additional_fields"
        case customFields = "custom_fields"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(catalogPriceRulesCount, forKey: .catalogPriceRulesCount)
        try container.encodeIfPresent(additionalFields, forKey: .additionalFields)
        try container.encodeIfPresent(customFields, forKey: .customFields)
    }
}

