//
// ResponseOrderShipmentListResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ResponseOrderShipmentListResult: Codable, JSONEncodable, Hashable {

    public var shipmentCount: Int?
    public var shipment: [Shipment]?
    public var additionalFields: AnyCodable?
    public var customFields: AnyCodable?

    public init(shipmentCount: Int? = nil, shipment: [Shipment]? = nil, additionalFields: AnyCodable? = nil, customFields: AnyCodable? = nil) {
        self.shipmentCount = shipmentCount
        self.shipment = shipment
        self.additionalFields = additionalFields
        self.customFields = customFields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case shipmentCount = "shipment_count"
        case shipment
        case additionalFields = "additional_fields"
        case customFields = "custom_fields"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(shipmentCount, forKey: .shipmentCount)
        try container.encodeIfPresent(shipment, forKey: .shipment)
        try container.encodeIfPresent(additionalFields, forKey: .additionalFields)
        try container.encodeIfPresent(customFields, forKey: .customFields)
    }
}

