//
// ResponseBatchJobListResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ResponseBatchJobListResult: Codable, JSONEncodable, Hashable {

    public var jobs: [BatchJob]?
    public var additionalFields: AnyCodable?
    public var customFields: AnyCodable?

    public init(jobs: [BatchJob]? = nil, additionalFields: AnyCodable? = nil, customFields: AnyCodable? = nil) {
        self.jobs = jobs
        self.additionalFields = additionalFields
        self.customFields = customFields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case jobs
        case additionalFields = "additional_fields"
        case customFields = "custom_fields"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(jobs, forKey: .jobs)
        try container.encodeIfPresent(additionalFields, forKey: .additionalFields)
        try container.encodeIfPresent(customFields, forKey: .customFields)
    }
}

