//
// ResponseOrderStatusListResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ResponseOrderStatusListResult: Codable, JSONEncodable, Hashable {

    public var cartOrderStatuses: [Status]?
    public var additionalFields: AnyCodable?
    public var customFields: AnyCodable?

    public init(cartOrderStatuses: [Status]? = nil, additionalFields: AnyCodable? = nil, customFields: AnyCodable? = nil) {
        self.cartOrderStatuses = cartOrderStatuses
        self.additionalFields = additionalFields
        self.customFields = customFields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cartOrderStatuses = "cart_order_statuses"
        case additionalFields = "additional_fields"
        case customFields = "custom_fields"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(cartOrderStatuses, forKey: .cartOrderStatuses)
        try container.encodeIfPresent(additionalFields, forKey: .additionalFields)
        try container.encodeIfPresent(customFields, forKey: .customFields)
    }
}

