//
// ResponseCartScriptListResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ResponseCartScriptListResult: Codable, JSONEncodable, Hashable {

    public var totalCount: Int?
    public var scripts: [Script]?
    public var additionalFields: AnyCodable?
    public var customFields: AnyCodable?

    public init(totalCount: Int? = nil, scripts: [Script]? = nil, additionalFields: AnyCodable? = nil, customFields: AnyCodable? = nil) {
        self.totalCount = totalCount
        self.scripts = scripts
        self.additionalFields = additionalFields
        self.customFields = customFields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case totalCount = "total_count"
        case scripts
        case additionalFields = "additional_fields"
        case customFields = "custom_fields"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(totalCount, forKey: .totalCount)
        try container.encodeIfPresent(scripts, forKey: .scripts)
        try container.encodeIfPresent(additionalFields, forKey: .additionalFields)
        try container.encodeIfPresent(customFields, forKey: .customFields)
    }
}

