//
// TaxClassRate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TaxClassRate: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var name: String?
    public var tax: Double?
    public var taxType: Int?
    public var taxBasedOn: String?
    public var countries: [TaxClassCountries]?
    public var cities: [String]?
    public var address: [String]?
    public var zipCodes: [TaxClassZipCodes]?
    public var additionalFields: AnyCodable?
    public var customFields: AnyCodable?

    public init(id: String? = nil, name: String? = nil, tax: Double? = nil, taxType: Int? = nil, taxBasedOn: String? = nil, countries: [TaxClassCountries]? = nil, cities: [String]? = nil, address: [String]? = nil, zipCodes: [TaxClassZipCodes]? = nil, additionalFields: AnyCodable? = nil, customFields: AnyCodable? = nil) {
        self.id = id
        self.name = name
        self.tax = tax
        self.taxType = taxType
        self.taxBasedOn = taxBasedOn
        self.countries = countries
        self.cities = cities
        self.address = address
        self.zipCodes = zipCodes
        self.additionalFields = additionalFields
        self.customFields = customFields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case tax
        case taxType = "tax_type"
        case taxBasedOn = "tax_based_on"
        case countries
        case cities
        case address
        case zipCodes = "zip_codes"
        case additionalFields = "additional_fields"
        case customFields = "custom_fields"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(tax, forKey: .tax)
        try container.encodeIfPresent(taxType, forKey: .taxType)
        try container.encodeIfPresent(taxBasedOn, forKey: .taxBasedOn)
        try container.encodeIfPresent(countries, forKey: .countries)
        try container.encodeIfPresent(cities, forKey: .cities)
        try container.encodeIfPresent(address, forKey: .address)
        try container.encodeIfPresent(zipCodes, forKey: .zipCodes)
        try container.encodeIfPresent(additionalFields, forKey: .additionalFields)
        try container.encodeIfPresent(customFields, forKey: .customFields)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension TaxClassRate: Identifiable {}
